<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://www.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.aws</groupId>
    <artifactId>aws-demo</artifactId>
    <version>1.0.0</version>

    <packaging>pom</packaging>

    <modules>
        <module>task01</module>
        <module>task02</module>
        <module>task03</module>
        <module>task04</module>
        <module>task05</module>
        <module>task06</module>
        <module>task07</module>
        <module>task08</module>
        <module>task09</module>
        <module>task10</module>

    </modules>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

</project>
